export const Colors = {
  primary: '#6C63FF',
  primaryDark: '#5A52E0',
  primaryLight: '#EEF0FF',
  secondary: '#FF6B6B',
  teal: '#4ECDC4',
  orange: '#FF9F43',
  green: '#2ECC71',
  yellow: '#F9CA24',
  background: '#F0F2F5',
  card: '#FFFFFF',
  border: '#E5E7EB',
  text: '#1A1A2E',
  textLight: '#6B7280',
  textMuted: '#9CA3AF',
  white: '#FFFFFF',
  tabBar: '#FFFFFF',
  tabBarBorder: '#E5E7EB',
};
