-- ============================================================================
-- Migration 007: Agent Sessions (Session Memory)
--
-- Stores what happens during a single tutoring session — one sitting where
-- a student opens the app, works through problems, and leaves.
--
-- Read at session start → builds session context for the agent.
-- Written after every problem → updates session state.
-- Read at next session start → agent loads recent session summaries.
--
-- Named agent_sessions (not tutoring_sessions) because tutoring_sessions
-- already exists from migration 001 and is used by the legacy endpoints.
-- The agent system gets its own session table with a different design.
--
-- Depends on: 006_student_profiles.sql (student_profiles table)
-- ============================================================================


-- ─── Table ────────────────────────────────────────────────────────────────────

CREATE TABLE agent_sessions (

    -- ── Session Identity ─────────────────────────────────────────────────────
    -- Which student, and is this session still in progress?

    id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),

    student_id  TEXT NOT NULL REFERENCES student_profiles(student_id) ON DELETE CASCADE,

    is_active   BOOLEAN NOT NULL DEFAULT true,
        -- Only one session per student can be active at a time.
        -- Enforced by partial unique index below.

    -- ── Session Timing ───────────────────────────────────────────────────────

    started_at       TIMESTAMPTZ NOT NULL DEFAULT now(),

    ended_at         TIMESTAMPTZ,
        -- NULL while session is active. Set when is_active flips to false.

    duration_minutes INT,
        -- Computed when session ends: extract(epoch from ended_at - started_at) / 60.
        -- NULL while session is active.

    -- ── Session State (core working data) ────────────────────────────────────
    -- The main JSONB blob the agent reads and writes during a session.
    -- Default includes full structure with empty arrays and zero counters
    -- so Python code never has to handle missing keys.

    session_state JSONB NOT NULL DEFAULT '{
        "problems_attempted": [],
        "current_mode": "socratic",
        "streak": 0,
        "frustration_signals": 0,
        "topics_covered": [],
        "mode_switches": 0
    }'::jsonb,
        -- problems_attempted[]: array of problem entries, each containing:
        --   expression, type, chapter, result, hints_used, mode_used,
        --   mode_source, time_seconds, error_types[], iterations_used, timestamp
        --
        -- result: "correct" | "correct_with_hints" | "incorrect" | "abandoned"
        -- mode_source: "student_selected" | "agent_determined"
        -- error_types: specific mistakes like "forgot_sum_formula"
        --
        -- current_mode: the mode currently active ("socratic", "direct", "concept_first")
        -- streak: consecutive correct answers, resets to 0 on incorrect
        -- frustration_signals: increments on 2+ wrong in a row, short messages, slow responses
        -- topics_covered: unique topic types seen this session
        -- mode_switches: how many times the mode changed this session

    -- ── Session Summary ──────────────────────────────────────────────────────
    -- Generated by post-session analysis. The agent reads ONLY these summaries
    -- from the last 5 sessions — not full session_state. Saves thousands of
    -- tokens while giving the agent a narrative arc of recent progress.

    session_summary TEXT,
        -- NULL while session is active. Filled at session end.
        -- Example: "Student practiced double angle identities and Pythagorean
        -- identities. Strong improvement on double angles — went from needing
        -- 2 hints to solving independently. Still needs work on factoring."

    -- ── Session Analytics ────────────────────────────────────────────────────
    -- Denormalized counters for quick queries without parsing JSONB.

    total_problems       INT NOT NULL DEFAULT 0,
    correct_count        INT NOT NULL DEFAULT 0,

    session_success_rate FLOAT NOT NULL DEFAULT 0.0
                         CHECK (session_success_rate >= 0.0 AND session_success_rate <= 1.0),

    avg_time_per_problem FLOAT,
        -- Average seconds per problem. NULL until first problem completed.

    -- ── Metadata ─────────────────────────────────────────────────────────────

    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);


-- ─── Indexes ──────────────────────────────────────────────────────────────────

-- Enforce: only one active session per student at a time.
-- Supabase rejects any INSERT that tries to create a second active session.
-- The app must deactivate the old session before starting a new one.
CREATE UNIQUE INDEX idx_one_active_session_per_student
    ON agent_sessions (student_id) WHERE is_active = true;

-- Find the active session quickly (used every request).
CREATE INDEX idx_agent_sessions_active
    ON agent_sessions (student_id) WHERE is_active = true;

-- Get last N sessions for a student (used at session start to load summaries).
CREATE INDEX idx_agent_sessions_student_recent
    ON agent_sessions (student_id, started_at DESC);


-- ─── Updated_at Trigger ───────────────────────────────────────────────────────
-- Reuses the update_updated_at() function from migration 001.

CREATE TRIGGER set_updated_at
    BEFORE UPDATE ON agent_sessions
    FOR EACH ROW EXECUTE FUNCTION update_updated_at();


-- ─── Row-Level Security ───────────────────────────────────────────────────────

ALTER TABLE agent_sessions ENABLE ROW LEVEL SECURITY;

-- Students can read their own sessions.
CREATE POLICY "Students can read their own sessions"
    ON agent_sessions FOR SELECT
    USING (auth.uid()::text = student_id);

-- Service role has full access (FastAPI backend uses service role key).
CREATE POLICY "Service role has full access to agent_sessions"
    ON agent_sessions FOR ALL
    USING (auth.role() = 'service_role');


-- ─── Helper Function ──────────────────────────────────────────────────────────
-- Returns recent session summaries for a student. The agent calls this at
-- session start via Supabase RPC to load narrative context without pulling
-- full session_state blobs.

CREATE OR REPLACE FUNCTION get_recent_session_summaries(
    p_student_id TEXT,
    p_count INT DEFAULT 5
)
RETURNS TABLE (
    session_summary TEXT,
    started_at      TIMESTAMPTZ,
    total_problems  INT,
    session_success_rate FLOAT
)
AS $$
BEGIN
    RETURN QUERY
    SELECT
        s.session_summary,
        s.started_at,
        s.total_problems,
        s.session_success_rate
    FROM agent_sessions s
    WHERE s.student_id = p_student_id
      AND s.is_active = false
      AND s.session_summary IS NOT NULL
    ORDER BY s.started_at DESC
    LIMIT p_count;
END;
$$ LANGUAGE plpgsql STABLE;


-- ─── Seed Data ────────────────────────────────────────────────────────────────
-- Two completed sessions and one active session for test_student_001.
-- Gives the agent realistic recent history to work with.

-- Session 1: 5 days ago, 25 minutes, 3 problems
INSERT INTO agent_sessions (
    student_id, is_active, started_at, ended_at, duration_minutes,
    session_state, session_summary,
    total_problems, correct_count, session_success_rate, avg_time_per_problem
) VALUES (
    'test_student_001',
    false,
    now() - interval '5 days',
    now() - interval '5 days' + interval '25 minutes',
    25,
    '{
        "problems_attempted": [
            {
                "expression": "verify sin(2θ) = 2sinθcosθ",
                "type": "double_angle",
                "chapter": 5,
                "result": "correct_with_hints",
                "hints_used": 2,
                "mode_used": "socratic",
                "mode_source": "agent_determined",
                "time_seconds": 320,
                "error_types": ["forgot_sum_formula"],
                "iterations_used": 4,
                "timestamp": null
            },
            {
                "expression": "simplify cos(2θ) using double angle formula",
                "type": "double_angle",
                "chapter": 5,
                "result": "correct",
                "hints_used": 0,
                "mode_used": "socratic",
                "mode_source": "agent_determined",
                "time_seconds": 180,
                "error_types": [],
                "iterations_used": 2,
                "timestamp": null
            },
            {
                "expression": "prove sin²θ + cos²θ = 1 from unit circle",
                "type": "pythagorean_identity",
                "chapter": 4,
                "result": "incorrect",
                "hints_used": 3,
                "mode_used": "socratic",
                "mode_source": "agent_determined",
                "time_seconds": 400,
                "error_types": ["forgot_to_factor"],
                "iterations_used": 5,
                "timestamp": null
            }
        ],
        "current_mode": "socratic",
        "streak": 0,
        "frustration_signals": 1,
        "topics_covered": ["double_angle", "pythagorean_identity"],
        "mode_switches": 0
    }'::jsonb,
    'Practiced double angles and Pythagorean identities. Improved on double angles from needing hints to independent solving. Struggled with Pythagorean identity — forgot factoring step.',
    3, 2, 0.67, 300.0
);

-- Session 2: 2 days ago, 30 minutes, 4 problems
INSERT INTO agent_sessions (
    student_id, is_active, started_at, ended_at, duration_minutes,
    session_state, session_summary,
    total_problems, correct_count, session_success_rate, avg_time_per_problem
) VALUES (
    'test_student_001',
    false,
    now() - interval '2 days',
    now() - interval '2 days' + interval '30 minutes',
    30,
    '{
        "problems_attempted": [
            {
                "expression": "verify 1 + tan²θ = sec²θ",
                "type": "pythagorean_identity",
                "chapter": 4,
                "result": "correct_with_hints",
                "hints_used": 1,
                "mode_used": "concept_first",
                "mode_source": "student_selected",
                "time_seconds": 240,
                "error_types": [],
                "iterations_used": 3,
                "timestamp": null
            },
            {
                "expression": "simplify (1 - cos²θ)/sinθ",
                "type": "pythagorean_identity",
                "chapter": 4,
                "result": "correct",
                "hints_used": 0,
                "mode_used": "socratic",
                "mode_source": "agent_determined",
                "time_seconds": 150,
                "error_types": [],
                "iterations_used": 2,
                "timestamp": null
            },
            {
                "expression": "express sin(A+B) + sin(A-B) as a product",
                "type": "sum_to_product",
                "chapter": 5,
                "result": "incorrect",
                "hints_used": 3,
                "mode_used": "socratic",
                "mode_source": "agent_determined",
                "time_seconds": 360,
                "error_types": ["wrong_formula_applied"],
                "iterations_used": 5,
                "timestamp": null
            },
            {
                "expression": "convert cos3θ + cosθ to product form",
                "type": "sum_to_product",
                "chapter": 5,
                "result": "correct_with_hints",
                "hints_used": 2,
                "mode_used": "direct",
                "mode_source": "student_selected",
                "time_seconds": 280,
                "error_types": [],
                "iterations_used": 3,
                "timestamp": null
            }
        ],
        "current_mode": "direct",
        "streak": 1,
        "frustration_signals": 1,
        "topics_covered": ["pythagorean_identity", "sum_to_product"],
        "mode_switches": 2
    }'::jsonb,
    'Reviewed Pythagorean identities with concept-first approach — student self-selected this mode and it worked well. Introduced sum-to-product formulas — struggled initially but got it with direct instruction. Student switches to Direct when frustrated.',
    4, 3, 0.75, 257.5
);

-- Session 3: Active (current session, no problems yet)
INSERT INTO agent_sessions (
    student_id, is_active, started_at
) VALUES (
    'test_student_001',
    true,
    now()
);
